const multipartErrorCodes = [
  'FST_FIELDS_LIMIT',
  'FST_FILE_BUFFER_NOT_FOUND',
  'FST_FILES_LIMIT',
  'FST_INVALID_JSON_FIELD_ERROR',
  'FST_INVALID_MULTIPART_CONTENT_TYPE',
  'FST_NO_FORM_DATA',
  'FST_PARTS_LIMIT',
  'FST_PROTO_VIOLATION',
  'FST_REQ_FILE_TOO_LARGE',
]

export {
  multipartErrorCodes,
}
